import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowRight, Check, Edit3, Eye, Filter, Plus, Search, UserRound, UserRoundX, X } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { getGetAdminSummaryQueryKey, getListParentsQueryKey, getListStudentsQueryKey, useCreateStudent, useListParents, useListStudents, useUpdateStudent, type Student, type StudentInput } from '@workspace/api-client-react';
import { Link } from 'react-router-dom';
import { AdminButton, AdminError, AdminLoading, AdminPageHeader, EmptyState, formatCurrency } from '@/components/admin';

const emptyStudent: StudentInput = { firstName: '', lastName: '', admissionNo: '', dateOfBirth: '', className: '', section: '', rollNumber: 1, parentIds: [], active: true };

function StudentFormDialog({ student, onClose }: { student?: Student; onClose: () => void }) {
  const queryClient = useQueryClient();
  const [form, setForm] = useState<StudentInput>(student ? { firstName: student.firstName, lastName: student.lastName, admissionNo: student.admissionNo, dateOfBirth: student.dateOfBirth, className: student.className, section: student.section, rollNumber: student.rollNumber, parentIds: student.parents.map(parent => parent.id), active: student.active } : emptyStudent);
  const parentsQuery = useListParents();
  const createStudent = useCreateStudent();
  const updateStudent = useUpdateStudent();
  const isPending = createStudent.isPending || updateStudent.isPending;
  const [error, setError] = useState('');
  useEffect(() => { setForm(student ? { firstName: student.firstName, lastName: student.lastName, admissionNo: student.admissionNo, dateOfBirth: student.dateOfBirth, className: student.className, section: student.section, rollNumber: student.rollNumber, parentIds: student.parents.map(parent => parent.id), active: student.active } : emptyStudent); }, [student]);
  const update = (key: keyof StudentInput, value: string | number | boolean | string[]) => setForm(current => ({ ...current, [key]: value }));
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setError('');
    const onSuccess = () => {
      queryClient.invalidateQueries({ queryKey: getListStudentsQueryKey() });
      queryClient.invalidateQueries({ queryKey: getListParentsQueryKey() });
      queryClient.invalidateQueries({ queryKey: getGetAdminSummaryQueryKey() });
      onClose();
    };
    const onError = () => setError('We could not save this student. Check the details and try again.');
    if (student) updateStudent.mutate({ studentId: student.id, data: { ...form, rollNumber: Number(form.rollNumber) } }, { onSuccess, onError });
    else createStudent.mutate({ data: { ...form, rollNumber: Number(form.rollNumber) } }, { onSuccess, onError });
  };
  if (!parentsQuery.data && parentsQuery.isLoading) return <div className="fixed inset-0 z-50 grid place-items-center admin-overlay p-4"><div className="admin-card w-full max-w-lg p-8"><div className="h-5 w-40 animate-pulse rounded bg-[hsl(var(--admin-ink)/.1)]" /><div className="mt-5 h-28 animate-pulse rounded bg-[hsl(var(--admin-ink)/.07)]" /></div></div>;
  return <div className="fixed inset-0 z-50 flex items-end justify-center admin-overlay p-0 sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-label={student ? 'Edit student' : 'Add student'}>
    <div className="max-h-[92dvh] w-full max-w-2xl overflow-y-auto rounded-t-[1.35rem] bg-[hsl(var(--admin-cream))] p-6 shadow-2xl sm:rounded-[1.35rem] sm:p-8">
      <div className="flex items-start justify-between gap-4"><div><div className="admin-eyebrow">{student ? 'Update record' : 'New record'}</div><h2 className="mt-2 font-display text-3xl">{student ? 'Edit student details' : 'Add a student'}</h2><p className="mt-2 text-sm text-[hsl(var(--admin-ink)/.55)]">One record connects class, family, fees and learning history.</p></div><button onClick={onClose} className="focus-ring rounded-full p-2 text-[hsl(var(--admin-ink)/.48)] hover:bg-white hover:text-[hsl(var(--admin-ink))]" aria-label="Close student form" data-testid="button-close-student-form"><X size={19} /></button></div>
      <form onSubmit={submit} className="mt-7 space-y-5">
        <div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold">First name<input required value={form.firstName} onChange={e => update('firstName', e.target.value)} className="admin-input mt-2" placeholder="e.g. Mira" data-testid="input-student-first-name" /></label><label className="text-xs font-bold">Last name<input required value={form.lastName} onChange={e => update('lastName', e.target.value)} className="admin-input mt-2" placeholder="e.g. Rao" data-testid="input-student-last-name" /></label></div>
        <div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold">Admission number<input required value={form.admissionNo} onChange={e => update('admissionNo', e.target.value)} className="admin-input mt-2" placeholder="PPS-2025-041" data-testid="input-student-admission-number" /></label><label className="text-xs font-bold">Date of birth<input required type="date" value={form.dateOfBirth.slice(0, 10)} onChange={e => update('dateOfBirth', e.target.value)} className="admin-input mt-2" data-testid="input-student-date-of-birth" /></label></div>
        <div className="grid gap-4 sm:grid-cols-[1fr_1fr_.7fr]"><label className="text-xs font-bold">Class<input required value={form.className} onChange={e => update('className', e.target.value)} className="admin-input mt-2" placeholder="Year 7" data-testid="input-student-class" /></label><label className="text-xs font-bold">Section<input required value={form.section} onChange={e => update('section', e.target.value)} className="admin-input mt-2" placeholder="A" data-testid="input-student-section" /></label><label className="text-xs font-bold">Roll no.<input required min="1" type="number" value={form.rollNumber} onChange={e => update('rollNumber', Number(e.target.value))} className="admin-input mt-2" data-testid="input-student-roll-number" /></label></div>
        <fieldset><legend className="text-xs font-bold">Link guardians <span className="font-normal text-[hsl(var(--admin-ink)/.45)]">(optional)</span></legend><div className="mt-2 grid gap-2 rounded-xl border border-[hsl(var(--admin-ink)/.1)] bg-white/45 p-3 sm:grid-cols-2">{(parentsQuery.data ?? []).map(parent => <label key={parent.id} className="flex cursor-pointer items-center gap-2 rounded-lg p-2 text-xs hover:bg-white"><input type="checkbox" checked={form.parentIds.includes(parent.id)} onChange={e => update('parentIds', e.target.checked ? [...form.parentIds, parent.id] : form.parentIds.filter(id => id !== parent.id))} className="accent-[hsl(var(--admin-teal))]" data-testid={`checkbox-student-parent-${parent.id}`} /><span className="font-semibold">{parent.firstName} {parent.lastName}</span><span className="text-[hsl(var(--admin-ink)/.45)]">· {parent.relationship}</span></label>)}{!parentsQuery.data?.length && <span className="p-2 text-xs text-[hsl(var(--admin-ink)/.5)]">No family records yet. You can link one later.</span>}</div></fieldset>
        <label className="flex cursor-pointer items-center gap-3 border-t border-[hsl(var(--admin-ink)/.1)] pt-5 text-xs font-bold"><input type="checkbox" checked={form.active} onChange={e => update('active', e.target.checked)} className="h-4 w-4 accent-[hsl(var(--admin-teal))]" data-testid="checkbox-student-active" />Student is active on the register</label>
        {error && <div className="rounded-lg bg-[hsl(var(--admin-coral)/.12)] p-3 text-xs font-semibold text-[hsl(var(--admin-coral))]" role="alert" data-testid="status-student-form-error">{error}</div>}
        <div className="flex justify-end gap-3 border-t border-[hsl(var(--admin-ink)/.1)] pt-5"><AdminButton onClick={onClose} variant="quiet">Cancel</AdminButton><AdminButton type="submit" disabled={isPending} icon={isPending ? undefined : <Check size={15} />}>{isPending ? 'Saving…' : student ? 'Save changes' : 'Add student'}</AdminButton></div>
      </form>
    </div>
  </div>;
}

function StudentRow({ student, onEdit, onToggle }: { student: Student; onEdit: () => void; onToggle: () => void }) {
  return <div className="group grid gap-4 border-b border-[hsl(var(--admin-ink)/.08)] px-5 py-4 last:border-0 hover:bg-white/40 sm:grid-cols-[minmax(190px,1.5fr)_1fr_1.3fr_.75fr_.75fr_auto] sm:items-center sm:px-6" data-testid={`row-student-${student.id}`}>
    <div className="flex min-w-0 items-center gap-3"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full font-mono-school text-[.6rem] font-bold ${student.active ? 'bg-[hsl(var(--admin-teal)/.14)] text-[hsl(var(--admin-teal))]' : 'bg-[hsl(var(--admin-ink)/.08)] text-[hsl(var(--admin-ink)/.5)]'}`}>{student.firstName.slice(0, 1)}{student.lastName.slice(0, 1)}</span><span className="min-w-0"><Link to={`/admin/students/${student.id}`} className="focus-ring block truncate text-sm font-bold hover:text-[hsl(var(--admin-teal))]" data-testid={`link-student-name-${student.id}`}>{student.firstName} {student.lastName}</Link><span className="mt-1 block font-mono-school text-[.58rem] text-[hsl(var(--admin-ink)/.45)]">{student.admissionNo}</span></span></div>
    <div><span className="text-xs font-semibold">{student.className} · {student.section}</span><span className="mt-1 block text-[.65rem] text-[hsl(var(--admin-ink)/.45)]">Roll {student.rollNumber}</span></div>
    <div className="flex flex-wrap gap-1.5">{student.parents.length ? student.parents.slice(0, 2).map(parent => <span key={parent.id} className="rounded-full bg-[hsl(var(--admin-teal)/.1)] px-2 py-1 text-[.62rem] font-semibold text-[hsl(var(--admin-teal))]">{parent.name}</span>) : <span className="text-xs text-[hsl(var(--admin-ink)/.4)]">No guardian linked</span>}</div>
    <div><span className={`text-sm font-bold ${student.attendance.percentage < 85 ? 'text-[hsl(var(--admin-coral))]' : 'text-[hsl(var(--admin-ink))]'}`}>{student.attendance.percentage}%</span><span className="mt-1 block text-[.62rem] text-[hsl(var(--admin-ink)/.45)]">attendance</span></div>
    <div><span className={`text-sm font-bold ${student.fees.due ? 'text-[hsl(var(--admin-coral))]' : 'text-[hsl(var(--admin-teal))]'}`}>{formatCurrency(student.fees.due)}</span><span className="mt-1 block text-[.62rem] text-[hsl(var(--admin-ink)/.45)]">fees due</span></div>
    <div className="flex items-center gap-1 opacity-100 sm:opacity-70 sm:group-hover:opacity-100"><Link to={`/admin/students/${student.id}`} className="focus-ring rounded-lg p-2 text-[hsl(var(--admin-ink)/.55)] hover:bg-[hsl(var(--admin-teal)/.1)] hover:text-[hsl(var(--admin-teal))]" aria-label={`View ${student.firstName} ${student.lastName}`} data-testid={`button-view-student-${student.id}`}><Eye size={15} /></Link><button onClick={onEdit} className="focus-ring rounded-lg p-2 text-[hsl(var(--admin-ink)/.55)] hover:bg-[hsl(var(--admin-teal)/.1)] hover:text-[hsl(var(--admin-teal))]" aria-label={`Edit ${student.firstName} ${student.lastName}`} data-testid={`button-edit-student-${student.id}`}><Edit3 size={15} /></button><button onClick={onToggle} className="focus-ring rounded-lg p-2 text-[hsl(var(--admin-ink)/.55)] hover:bg-[hsl(var(--admin-coral)/.1)] hover:text-[hsl(var(--admin-coral))]" aria-label={`${student.active ? 'Deactivate' : 'Activate'} ${student.firstName} ${student.lastName}`} data-testid={`button-toggle-student-${student.id}`}>{student.active ? <UserRoundX size={15} /> : <UserRound size={15} />}</button></div>
  </div>;
}

export default function StudentsPage() {
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState<'all' | 'active' | 'inactive'>('all');
  const [formOpen, setFormOpen] = useState(false);
  const [editing, setEditing] = useState<Student | undefined>();
  const [toggleTarget, setToggleTarget] = useState<Student | undefined>();
  const queryClient = useQueryClient();
  const studentsQuery = useListStudents({ search: search || undefined, status: status === 'all' ? undefined : status });
  const updateStudent = useUpdateStudent();
  const shown = useMemo(() => studentsQuery.data ?? [], [studentsQuery.data]);
  const toggle = () => {
    if (!toggleTarget) return;
    updateStudent.mutate({ studentId: toggleTarget.id, data: { firstName: toggleTarget.firstName, lastName: toggleTarget.lastName, admissionNo: toggleTarget.admissionNo, dateOfBirth: toggleTarget.dateOfBirth, className: toggleTarget.className, section: toggleTarget.section, rollNumber: toggleTarget.rollNumber, parentIds: toggleTarget.parents.map(parent => parent.id), active: !toggleTarget.active } }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListStudentsQueryKey() }); queryClient.invalidateQueries({ queryKey: getGetAdminSummaryQueryKey() }); setToggleTarget(undefined); } });
  };
  return <div className="p-5 sm:p-8 lg:p-10">
    <AdminPageHeader eyebrow="People · student register" title="Every learner, one story." description="Keep class placement, family relationships and the day-to-day signals of student life close at hand." action={<AdminButton onClick={() => { setEditing(undefined); setFormOpen(true); }} icon={<Plus size={15} />} variant="coral">Add student</AdminButton>} />
    <div className="mt-7 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><label className="relative block min-w-0 flex-1 lg:max-w-md"><Search size={16} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[hsl(var(--admin-ink)/.4)]" /><span className="sr-only">Search students</span><input type="search" value={search} onChange={e => setSearch(e.target.value)} className="admin-input pl-9" placeholder="Search by name or admission number" data-testid="input-search-students" /></label><div className="flex items-center gap-2"><Filter size={15} className="text-[hsl(var(--admin-ink)/.4)]" /><div className="flex rounded-lg border border-[hsl(var(--admin-ink)/.12)] bg-white/55 p-1">{(['all', 'active', 'inactive'] as const).map(item => <button onClick={() => setStatus(item)} key={item} className={`focus-ring rounded-md px-3 py-2 text-[.68rem] font-bold capitalize ${status === item ? 'bg-[hsl(var(--admin-ink))] text-white' : 'text-[hsl(var(--admin-ink)/.55)] hover:text-[hsl(var(--admin-ink))]'}`} data-testid={`button-filter-students-${item}`}>{item}</button>)}</div><span className="ml-2 font-mono-school text-[.65rem] text-[hsl(var(--admin-ink)/.45)]">{shown.length} shown</span></div></div>
    <div className="admin-card mt-5 overflow-hidden">{studentsQuery.isLoading ? <div className="p-5"><AdminLoading /></div> : studentsQuery.isError ? <div className="p-5"><AdminError onRetry={() => studentsQuery.refetch()} /></div> : shown.length ? <><div className="hidden grid-cols-[minmax(190px,1.5fr)_1fr_1.3fr_.75fr_.75fr_auto] gap-4 border-b border-[hsl(var(--admin-ink)/.1)] px-6 py-3 font-mono-school text-[.58rem] uppercase tracking-[.1em] text-[hsl(var(--admin-ink)/.42)] sm:grid"><span>Student</span><span>Placement</span><span>Family links</span><span>Presence</span><span>Balance</span><span /></div>{shown.map(student => <StudentRow key={student.id} student={student} onEdit={() => { setEditing(student); setFormOpen(true); }} onToggle={() => setToggleTarget(student)} />)}</> : <EmptyState title="No students match that view" body="Try another name, admission number or register filter. New learners can be added in seconds." action={<AdminButton onClick={() => { setEditing(undefined); setFormOpen(true); }} icon={<Plus size={15} />}>Add the first student</AdminButton>} />}</div>
    {toggleTarget && <div className="fixed inset-0 z-50 grid place-items-center admin-overlay p-5"><div className="admin-card w-full max-w-sm p-7" role="dialog" aria-modal="true"><div className="admin-eyebrow">Confirm register change</div><h2 className="mt-3 font-display text-2xl">{toggleTarget.active ? 'Deactivate' : 'Activate'} {toggleTarget.firstName}?</h2><p className="mt-3 text-sm leading-6 text-[hsl(var(--admin-ink)/.58)]">{toggleTarget.active ? 'This will remove the learner from the active register while keeping their full history.' : 'This will return the learner to the active register.'}</p><div className="mt-7 flex justify-end gap-3"><AdminButton onClick={() => setToggleTarget(undefined)} variant="quiet">Cancel</AdminButton><AdminButton onClick={toggle} disabled={updateStudent.isPending} variant={toggleTarget.active ? 'coral' : 'primary'}>{updateStudent.isPending ? 'Updating…' : toggleTarget.active ? 'Deactivate' : 'Activate'}</AdminButton></div></div></div>}
    {formOpen && <StudentFormDialog student={editing} onClose={() => { setFormOpen(false); setEditing(undefined); }} />}
  </div>;
}