import { ArrowLeft, CalendarDays, CheckCircle2, CircleDollarSign, ClipboardCheck, Mail, Phone, UserRound } from 'lucide-react';
import { useGetStudent, getGetStudentQueryKey } from '@workspace/api-client-react';
import { Link, useParams } from 'react-router-dom';
import { AdminError, AdminLoading, AdminPageHeader, formatCurrency } from '@/components/admin';

export default function StudentProfilePage() {
  const { studentId = '' } = useParams<{ studentId: string }>();
  const studentQuery = useGetStudent(studentId, { query: { queryKey: getGetStudentQueryKey(studentId), enabled: Boolean(studentId) } });
  if (studentQuery.isLoading) return <div className="p-5 sm:p-8"><AdminLoading /></div>;
  if (studentQuery.isError || !studentQuery.data) return <div className="p-5 sm:p-8"><AdminError onRetry={() => studentQuery.refetch()} /></div>;
  const student = studentQuery.data;
  const profileStatusClass = student.active ? 'bg-[hsl(var(--admin-teal)/.12)] text-[hsl(var(--admin-teal))]' : 'bg-[hsl(var(--admin-ink)/.09)] text-[hsl(var(--admin-ink)/.6)]';
  const profileDotClass = student.active ? 'bg-[hsl(var(--admin-teal))]' : 'bg-[hsl(var(--admin-ink)/.4)]';
  return <div className="p-5 sm:p-8 lg:p-10">
    <Link to="/admin/students" className="focus-ring inline-flex items-center gap-2 text-xs font-bold text-[hsl(var(--admin-ink)/.55)] hover:text-[hsl(var(--admin-teal))]" data-testid="link-profile-back-students"><ArrowLeft size={14} />Back to student register</Link>
    <div className="mt-6"><AdminPageHeader eyebrow={`Student profile · ${student.admissionNo}`} title={`${student.firstName} ${student.lastName}`} description="The full family, classroom and progress story — together, without duplicate entry." action={<span className={`inline-flex items-center gap-2 rounded-full px-3 py-2 text-xs font-bold ${profileStatusClass}`} data-testid="status-student-profile-active"><span className={`h-2 w-2 rounded-full ${profileDotClass}`} />{student.active ? 'Active on register' : 'Inactive record'}</span>} /></div>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      {[{label: 'Class placement', value: `${student.className} · ${student.section}`, detail: `Roll number ${student.rollNumber}`, icon: UserRound}, {label: 'Attendance', value: `${student.attendance.percentage}%`, detail: `${student.attendance.present} present · ${student.attendance.absent} absent`, icon: ClipboardCheck}, {label: 'Fee balance', value: formatCurrency(student.fees.due), detail: student.fees.nextDue ? `Next due ${new Date(student.fees.nextDue).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}` : 'No upcoming due date', icon: CircleDollarSign}, {label: 'Date of birth', value: new Date(student.dateOfBirth).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }), detail: student.active ? 'Current student' : 'Historical record', icon: CalendarDays}].map(({label, value, detail, icon: Icon}) => <div className="admin-card p-5" key={label} data-testid={`profile-summary-${label.toLowerCase().replaceAll(' ', '-')}`}><div className="flex items-center gap-2 text-[.65rem] font-bold uppercase tracking-[.1em] text-[hsl(var(--admin-ink)/.48)]"><Icon size={15} className="text-[hsl(var(--admin-teal))]" />{label}</div><div className="mt-4 font-display text-2xl">{value}</div><div className="mt-1 text-xs text-[hsl(var(--admin-ink)/.5)]">{detail}</div></div>)}
    </section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.12fr_.88fr]">
      <div className="space-y-5">
        <div className="admin-card p-6 sm:p-7"><div className="flex items-center justify-between"><div><div className="admin-eyebrow">Family circle</div><h2 className="mt-2 font-display text-2xl">People to call first.</h2></div><span className="grid h-9 w-9 place-items-center rounded-lg bg-[hsl(var(--admin-coral)/.12)] text-[hsl(var(--admin-coral))]"><UserRound size={17} /></span></div><div className="mt-6 space-y-3">{student.parents.length ? student.parents.map(parent => <div key={parent.id} className="flex items-center gap-3 rounded-xl border border-[hsl(var(--admin-ink)/.08)] bg-white/45 p-3" data-testid={`profile-guardian-${parent.id}`}><span className="grid h-9 w-9 place-items-center rounded-full bg-[hsl(var(--admin-coral)/.13)] font-mono-school text-[.58rem] font-bold text-[hsl(var(--admin-coral))]">{parent.name.split(' ').map(part => part.slice(0, 1)).join('').slice(0, 2)}</span><div className="min-w-0 flex-1"><div className="text-sm font-bold">{parent.name}</div><div className="mt-1 text-xs text-[hsl(var(--admin-ink)/.5)]">{parent.relationship}</div></div><a href={`tel:${parent.phone}`} className="focus-ring rounded-lg p-2 text-[hsl(var(--admin-teal))] hover:bg-[hsl(var(--admin-teal)/.1)]" aria-label={`Call ${parent.name}`} data-testid={`link-call-guardian-${parent.id}`}><Phone size={15} /></a></div>) : <div className="rounded-xl bg-[hsl(var(--admin-ink)/.04)] p-4 text-sm text-[hsl(var(--admin-ink)/.5)]">No guardian is linked to this student yet.</div>}</div></div>
        <div className="admin-card p-6 sm:p-7"><div className="admin-eyebrow">Learning map</div><h2 className="mt-2 font-display text-2xl">Subjects & teachers.</h2><div className="mt-6 grid gap-2 sm:grid-cols-2">{student.subjects.length ? student.subjects.map(subject => <div className="flex items-center justify-between rounded-xl bg-[hsl(var(--admin-teal)/.07)] p-3" key={subject.id} data-testid={`profile-subject-${subject.id}`}><span className="text-sm font-bold">{subject.name}</span><span className="text-[.68rem] text-[hsl(var(--admin-ink)/.5)]">{subject.teacher}</span></div>) : <div className="text-sm text-[hsl(var(--admin-ink)/.5)]">No subjects recorded yet.</div>}</div></div>
      </div>
      <div className="space-y-5">
        <div className="admin-card p-6 sm:p-7"><div className="admin-eyebrow">Academic pulse</div><h2 className="mt-2 font-display text-2xl">Recent results.</h2><div className="mt-6 divide-y divide-[hsl(var(--admin-ink)/.08)]">{student.results.length ? student.results.map(result => <div className="flex items-center gap-3 py-3 first:pt-0 last:pb-0" key={result.subject} data-testid={`profile-result-${result.subject.toLowerCase().replaceAll(' ', '-')}`}><span className="grid h-8 w-8 place-items-center rounded-lg bg-[hsl(var(--accent)/.22)] font-mono-school text-xs font-bold text-[hsl(34_63%_29%)]">{result.grade}</span><span className="flex-1 text-sm font-semibold">{result.subject}</span><span className="font-mono-school text-xs text-[hsl(var(--admin-ink)/.55)]">{result.score}%</span></div>) : <div className="text-sm text-[hsl(var(--admin-ink)/.5)]">No results recorded yet.</div>}</div></div>
        <div className="rounded-[1.1rem] bg-[hsl(var(--admin-ink))] p-6 text-white sm:p-7"><div className="flex items-center justify-between"><div className="admin-eyebrow text-[hsl(var(--accent))]">Fees at a glance</div><CircleDollarSign size={18} className="text-[hsl(var(--accent))]" /></div><div className="mt-4 flex items-end justify-between"><div><div className="font-display text-4xl">{formatCurrency(student.fees.due)}</div><div className="mt-1 text-xs text-white/55">outstanding balance</div></div><div className="text-right"><div className="font-mono-school text-xs text-[hsl(var(--accent))]">{formatCurrency(student.fees.paid)}</div><div className="mt-1 text-[.62rem] text-white/45">of {formatCurrency(student.fees.total)} paid</div></div></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/12"><div className="h-full rounded-full bg-[hsl(var(--accent))]" style={{ width: `${student.fees.total ? Math.min(100, student.fees.paid / student.fees.total * 100) : 0}%` }} /></div>{student.fees.nextDue && <div className="mt-5 flex items-center gap-2 text-xs text-white/58"><CalendarDays size={14} className="text-[hsl(var(--accent))]" />Next due {new Date(student.fees.nextDue).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</div>}</div>
      </div>
    </section>
    <div className="mt-7 flex flex-wrap gap-4 border-t border-[hsl(var(--admin-ink)/.1)] pt-6 text-xs text-[hsl(var(--admin-ink)/.5)]"><span className="flex items-center gap-2"><CheckCircle2 size={14} className="text-[hsl(var(--admin-teal))]" />All record sections are connected</span><a href="mailto:hello@paradisepublic.school" className="focus-ring flex items-center gap-2 font-bold hover:text-[hsl(var(--admin-teal))]" data-testid="link-profile-contact-office"><Mail size={14} />Contact family office</a></div>
  </div>;
}